### ISSUE TITLE
Formalising merge segmentation

### ISSUE THREAD

**Issue by sagar87** [sagar87/spatialproteomics#32]
I was thinking a bit about how one could go about merging segmentations using the `spatialproteomics` way:

```
# prepare segmentation masks
segmentation_object = (sprot
  .pp.drop(keep='image') # drop every layer except the image (optional)
  .pp[['marker A', 'marker B', 'marker C']] # select marker to segment on
  .tl.cellpose(key_added='_cellpose_segmentation')
  .pp.merge_segmentations(layer_key='_cellpose_segmentation', key_added='_merged')
)

final_object = (sprot
  .pp.drop(keep='image') # drop every layer except the image (optional)
  .pp.add_segmentation(segmentation_object._merged.values)
)
```

**Comment by sagar87** [comment]
From the discussion => avoid returning a `numpy` array => each accessor should return an `xarray` so that additional calls are possible and very unelegant

```
segmentation = (data['TMA1_Foll_FL-13']
                .pp.drop_layers(['_obs', '_segmentation'])
                .pp[['DAPI', 'CD35']]
                .tl.cellpose(key_added='_cellpose_segmentation')
                .pp.merge_segmentation(key='_cellpose_segmentation', key_added='_merged')
                .pp.add_segmentation(from_key ='merged')
)
```

**Comment by MeyerBender** [comment]
Here's the issue: there are several ways to segment with cellpose, either on one channel only (1), on a subset of the channels (2), or on all channels within the object (3).

For way 1, this works fine:
![image](https://github.com/sagar87/spatialproteomics/assets/62450528/fc8f6490-7491-40b5-9609-44ba5c8c712a)

Way 3 also works out of the box:
![image](https://github.com/sagar87/spatialproteomics/assets/62450528/11f442d6-1612-4090-8437-92c64c71f36d)

Way 2 currently prints the following error message:
![image](https://github.com/sagar87/spatialproteomics/assets/62450528/afc68071-4d2e-4c35-841a-8bdcb79a086d)

The problem is that if we were to segment on a subset of markers, we would need to introduce a new set of coordinates, which would be a subset of the channels. Would that be a reasonable solution? I could then extend the merge function to merge from a layer (such as `_cellpose_segmentation`) directly.

**Comment by sagar87** [comment]
`tl.cellpose` should only return two things either a `C x X x Y` or a `X x Y` array and nothing in between (this is the only way to keep things consistent). 

If a user wants to have a subset of masks he needs to create intermediate object i.e:

```
segmentation_object = (sprot
  .pp.drop(keep='image') # drop every layer except the image (optional)
  .pp[['marker A', 'marker B', 'marker C']] # select marker to segment on
  .tl.cellpose(key_added='_cellpose_segmentation')
)
```

**Comment by MeyerBender** [comment]
This is exactly what is currently implemented in way 3. So is this all sorted then? If so, I will simply adjust merge_segmentation to support merging directly from a layer, and that should address everything?
